# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=1.21.9
mapping_channel=official
yarn_mappings=1.21.9+build.1
loader_version=0.17.0
jade_version=20.0.2
jade_neo_version=19.1.0

# Mod Properties
mod_version=3.3.0-1.21.9-Fabric
forge_mod_version=3.3.0-1.21.9-Forge
neoforge_mod_version=3.3.0-1.21.9-NeoForge
mod_author=skniro
maven_group=com.skniro
archives_base_name=super_apple
archivesBaseName=super_apple
# Dependencies
# check this on https://modmuss50.me/fabric.html
#Fabric api
fabric_version=0.133.14+1.21.9
forge_version=59.0.0

# Neoforge Properties
minecraft_version_range=[1.21,1.22)
mod_id=agree
mod_name=Super Apple
mod_license=MIT License
mod_group_id=com.skniro.agree
mod_description=Add some special apple which is can give you some effect.
mod_authors=skniro

# Neoforge
neo_version=21.9.3-beta
neo_version_range=[21.0,)
loader_version_range=[2,)
forge_version_range=[2,)