# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=1.21.4
mapping_channel=official
yarn_mappings=1.21.4+build.1
loader_version=0.16.9

# Mod Properties
mod_version=3.2.14-1.21.4-Fabric
forge_mod_version=3.2.14-1.21.4-Forge
neoforge_mod_version=3.2.14-1.21.4-NeoForge
mod_author=skniro
maven_group=com.skniro
archives_base_name=super_apple
archivesBaseName=super_apple
# Dependencies
# check this on https://modmuss50.me/fabric.html
#Fabric api
fabric_version=0.111.0+1.21.4
forge_version=54.0.6

# Neoforge Properties
minecraft_version_range=[1.21,1.22)
mod_id=agree
mod_name=Super Apple
mod_license=MIT License
mod_group_id=com.skniro.agree
mod_description=Add some special apple which is can give you some effect.
mod_authors=skniro

# Neoforge
neo_version=21.4.10-beta
neo_version_range=[21.0,)
loader_version_range=[2,)